# Site settings
title: Resume
email: intentfilms+github@gmail.com
description: > # This is now place holder text before I say anything interesting to encourage GitHub to hire me. Woot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  bmbailey

# Build settings
markdown: kramdown
